  - alias: "Internet Speed Glow Connect Great"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.speedtest_download')|float > 10 }}"
    action:
      - service: shell_command.green

  - alias: "Internet Speed Glow Connect Poor"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.speedtest_download')|float < 10 }}"
    action:
      - service: shell_command.red
      
  - alias: "Turn on Fan"
    trigger:
      platform: numeric_state
      entity_id: sensor.studio_temperature
      above: '70'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.tile'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.black_panther'
          state: 'home'
    action:
      service: switch.turn_on
      entity_id: switch.temperature      
      
     

- alias: Test Join
      trigger:
        platform: state
        entity_id: input_boolean.activate_join
        to: 'on'
      action:
        service: text.join
      data:
        target:
          - 'Phone'
          - 'Browser'
          - 'Windows'
        title: <title>
        message: '<action>/[<phone-number>/]<data>'

- id: letsencrypt-renewal
  alias: "Let's Encrypt Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt


- alias: "Self Heal Disk Use Alarm"
    trigger:
      - platform: numeric_state
        entity_id: sensor.disk_use_percent_
        above: 80
    action:
      - service: script.notify_engine
        data_template:
          value1: 'Hard Drive Monitor:'
          value2: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_percent_.state }}%!"
          value3: 'Attempting to clean'
          who: 'carlo'
      - service: tts.clear_cache

  - alias: "Disk Use Alarm"
    trigger:
      - platform: numeric_state
        entity_id: sensor.disk_use_percent_
        above: 90
    action:
      - service: script.notify_engine
        data_template:
          value1: 'Hard Drive Monitor:'
          value2: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_percent_.state }}%!"
          who: 'carlo'

      - service: persistent_notification.create
        data:
          title: "Hard Drive Monitor:"
          message: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_percent_.state }}%!"
          notification_id: "Critical Alert"
          
  - alias: Interface - Set UI theme
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id:
          - alarm_control_panel.alarm
          - input_boolean.maintenance_mode
      - platform: state
        entity_id: input_boolean.dark
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '07:00:00'
    action:
      service: frontend.set_theme
      data_template:
        name: >
          {% if not is_state ('alarm_control_panel.alarm' , 'disarmed') %} darkred
          {% elif is_state ('input_boolean.maintenance_mode' , 'on') %} darkorange
          {% elif ((now().hour == 23) or (now().hour < 7)) %} darkcyan
          {% elif is_state('input_boolean.dark' , 'on') %} midnight
          {% else %} default {% endif %}
  - alias: Interface - UI Tiles update available
    trigger:
      platform: state
      entity_id: sensor.ui_tiles_version
    action:
      service: script.notify
      data:
        no_say: 1
        tell: mf
        call_tiles_update: 1

  - alias: Interface - Renew SSL certificate
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl

  - alias: Interface - SSL certificate expiry notification
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
    action:
      service: script.notify
      data:
        tell: mf
        no_say: 1
        message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'
        
- alias: Automatic Theme Change
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      - platform: state
        entity_id: sun.sun
        to: below_horizon
    action:
      - service_template: frontend.set_theme
        data_template:
          name: >
            {% if states.sun.sun.state == "above_horizon" %}
              default
            {% else %}
              darkred # <-- change to your dark theme name.
            {% endif %}
        