################################################################################
# Binary Sensors
################################################################################  
  

- platform: template
  period_of_day:
    friendly_name: 'Period of the Day'
    value_template: >-
      {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
        dusk
      {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
        dawn
      {% elif (states.sun.sun.attributes.elevation) < -4 %}
        night
      {% else %}
        day
      {% endif %}
    icon_template: >-
      {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
        mdi:weather-sunset-down
      {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
        mdi:weather-sunset-up
      {% elif (states.sun.sun.attributes.elevation) < -4 %}
        mdi:weather-night
      {% else %}
        mdi:weather-sunny
      {% endif %}

# Workday
- platform: workday
  name: workday
  country: US
  workdays: [fri, sat, sun]
  excludes: [mon, tue, wed, thu, holiday]
# Worknight
- platform: workday
  name: worknight
  country: US
  days_offset: 1
  workdays: [fri, sat, sun]
  excludes: [mon, tue, wed, thu, holiday]
  
- platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan
    
- platform: command_line
    name: WAN
    command: "/home/homeassistant/.homeassistant/wan_test.sh"
    device_class: connectivity
    payload_on: "Up"
    payload_off: "Down"    